# analysis_options.yaml – RAÍZ DEL MONOREPO
# Todos los packages heredan estas opciones con: include: ../../analysis_options.yaml
#
# Para overrides locales, cada package puede incluir este archivo y añadir
# sus propias reglas.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"
    - "build_web/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    eol_at_end_of_file: true
    missing_whitespace_between_adjacent_strings: true
    parameter_assignments: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    void_checks: true
