coverage:
  ignore:
    - "apps/client-app/lib/main.dart"
    - "apps/client-app/lib/app.dart"
    # Archivos generados
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/injectable.module.dart"
